### ISSUE TITLE
Read remote address leads to a segfault

### ISSUE THREAD

**Issue by hhxsv5** [hoaproject/Websocket#66]
Hello, how to get  the client ip address?

$bucket->getSource()->getConnection()->getRemoteAddress() ?

**Comment by Hywan** [comment]
Hello,

Yes, this is correct, but you must call `Hoa\Socket\Connection\Connection::considerRemoteAddress` before, because this is not automatic (thank you C API \o/).

**Comment by hhxsv5** [comment]
Thanks for your answer, I did as you said but I got an error **`[1]    1701 segmentation fault`**.

```PHP
$bucket->getSource()->getConnection()->considerRemoteAddress(true);
$bucket->getSource()->getConnection()->getRemoteAddress()
```

**Comment by Hywan** [comment]
It seems to be an error from PHP… Damn. Can you call the `considerRemoteAddress` method just after the constructor?

**Comment by Hywan** [comment]
We should also report this bug in the Zend Engine. Could you provide a minimal working example please?

**Comment by hhxsv5** [comment]
The error still exists when I call the `considerRemoteAddress ` method after the constructor.

My code:

```PHP
$server = new \Hoa\Websocket\Server(
    new \Hoa\Socket\Server('ws://10.0.0.229:8044')
);

// $server->getConnection()->considerRemoteAddress(true); // ERROR: 6758 segmentation fault

$server->on('open', function (\Hoa\Event\Bucket $bucket) {
    $conn = $bucket->getSource()->getConnection();
    // $conn->considerRemoteAddress(true); // ERROR: 6758 segmentation fault
    $addr = $conn->getRemoteAddress();
    echo 'New connection: ', var_export($addr, true), PHP_EOL;
});

$server->on('message', function (\Hoa\Event\Bucket $bucket) {
    echo 'onMessage: ', var_export($bucket->getData(), true), PHP_EOL;
});

$server->on('close', function (\Hoa\Event\Bucket $bucket) {
    echo 'onCLose: ', var_export($bucket->getData(), true), PHP_EOL;
});

$server->on('error', function (\Hoa\Event\Bucket $bucket) {
    echo 'onError: ', var_export($bucket->getData(), true), PHP_EOL;
});

$server->run();
```

Thank you.

**Comment by Hywan** [comment]
A segfault comes from the VM. What PHP VM and at what version are you using please?

**Comment by hhxsv5** [comment]
PHP Version 5.6.19
Docker PHP-FPM: php:5.6-fpm

**Comment by Hywan** [comment]
I found where the bug comes from. This is clearly from the VM. Digging a little bit more.

**Comment by Hywan** [comment]
Tested with PHP 5.5 and it works. This is a regression.

**Comment by hhxsv5** [comment]
Cool ! 
It's bug of PHP 5.6.19, please see [here](http://php.net/ChangeLog-5.php#5.6.20).
`Fixed bug #71596 (Segmentation fault on ZTS with date function (setlocale)).`

**Comment by Hywan** [comment]
This bug is still present since 5.6. So this is another one. And it's not related to date :-).

**Comment by Hywan** [comment]
Bug reported, https://bugs.php.net/72439.

**Comment by Hywan** [comment]
I have started a new thread on php-internals, https://marc.info/?l=php-internals&m=146616838528035&w=2.

**Comment by hhxsv5** [comment]
It seems that this bug has not been solved yet, I reappear the error on PHP 7.0.7. I will keep concerning it.
Finally,  many thanks for your help.

**Comment by Hywan** [comment]
@laruence has submitted a patch that fix this segmentation fault, https://git.php.net/?p=php-src.git;a=blobdiff;f=main/streams/xp_socket.c;h=90c5df0b8aa9f80c98197783f258e3473404a471;hp=995e90f98d7654dcaaa909b9bb7df5c3570fe4c5;hb=c4c1993af63fe4c0d19d44ebbd38996471c141af;hpb=ed0ec669968420ad0fa942c92d92b69a95e9beb1. https://bugs.php.net/bug.php?id=72439 is now marked as closed. I guess we can close this issue too? Would you like to test this patch first?

**Comment by hhxsv5** [comment]
Yeah, thank you.

**Comment by Hywan** [comment]
I did some tests to see if we can avoid the segmentation fault with pure PHP (as we did in [`Hoa\Iterator`](http://central.hoa-project.net/Resource/Library/Iterator)) but without any success, sorry for that 😞. Also, sorry for not having detected this regression in Zend Engine before, we would have been able to raise it before it officially lands 😞.
